import SimilarProducts from "@/web/components/Product/SimilarProducts"
import { CartContext } from "@/web/hooks/CartContext"
import axios from "axios"
import Head from "next/head"
import Image from "next/image"
import { useCallback, useContext } from "react"

export const getServerSideProps = async ({ params }) => {
  const id = params.id
  const { data } = await axios.get(
    `http://localhost:3000/api/backoffice/product/${id}`
  )

  return {
    props: { data },
  }
}

const Product = (props) => {
  const {
    data: { result },
  } = props

  const { addToCart } = useContext(CartContext)

  const handleAddToCart = useCallback(
    (product) => {
      addToCart(product)
    },
    [addToCart]
  )

  const getStockStatus = (quantity) => {
    if (quantity > 20) {
      return "In stock"
    } else if (quantity > 0) {
      return "Stock is low"
    } else {
      return "Out of stock"
    }
  }

  return (
    <>
      <Head>
        <title>AIRNEIS - {result.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between lg:flex-row">
        <Image
          alt="canape"
          width={550}
          height={550}
          src="/images/canape.jpg"
          className="w-full rounded-3xl p-4"
        />
        <div className="flex p-4">
          <div key={result.id} className="flex font-sans">
            <div className="flex-auto p-6">
              <div className="flex flex-wrap">
                <h1 className="flex-auto text-lg font-semibold text-slate-900">
                  {result.name}
                </h1>
                <div className="text-lg font-semibold text-slate-500">
                  {result.price} €
                </div>
                <div className="text-sm font-medium text-slate-500">
                  {getStockStatus(result.quantity)}
                </div>
              </div>

              <div className="mb-6 mt-4 flex items-baseline border-b border-slate-200 pb-6"></div>
              <p className="flex text-sm text-slate-700">
                {result.description}
              </p>

              <div className="mb-6 flex space-x-4 text-sm font-medium">
                <div className="flex flex-auto justify-end space-x-4">
                  <button
                    className={`h-10 rounded-md border border-slate-200 px-6 font-semibold text-slate-900 ${
                      result.quantity === 0 ? "bg-gray-300" : "bg-orange-100"
                    }`}
                    onClick={() => handleAddToCart(result)}
                    disabled={result.quantity === 0}
                  >
                    {result.quantity === 0 ? "Out of stock" : "Add to cart"}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <SimilarProducts category={result.category} />
    </>
  )
}

Product.isPublicPage = true
export default Product
