import axios from "axios"
import Head from "next/head"
import Image from "next/image"

const products = [
  {
    id: 1,
    name: "Canapé 1",
    price: "111 €",
    img: (
      <Image
        alt="canape"
        width={300}
        height={300}
        src="/images/canape.jpg"
        className="rounded-lg hover:opacity-50"
      />
    ),
  },
  {
    id: 2,
    name: "Canapé 2",
    price: "222 €",
    img: (
      <Image
        alt="lit"
        width={300}
        height={300}
        src="/images/lit.jpg"
        className="rounded-lg hover:opacity-50"
      />
    ),
  },
  {
    id: 3,
    name: "Canapé 3",
    price: "333 €",
    img: (
      <Image
        alt="table"
        width={300}
        height={300}
        src="/images/table.jpg"
        className="rounded-lg duration-300 hover:opacity-50"
      />
    ),
  },
  {
    id: 4,
    name: "Canapé 4",
    price: "444 €",
    img: (
      <Image
        alt="bureau"
        width={300}
        height={300}
        src="/images/bureau.jpg"
        className="rounded-lg duration-300 hover:opacity-50"
      />
    ),
  },
  {
    id: 5,
    name: "Canapé 5",
    price: "555 €",
    img: (
      <Image
        alt="canape"
        width={300}
        height={300}
        src="/images/canape.jpg"
        className="rounded-lg duration-300 hover:opacity-50"
      />
    ),
  },
  {
    id: 6,
    name: "Canapé 6",
    price: "666 €",
    img: (
      <Image
        alt="lit"
        width={300}
        height={300}
        src="/images/lit.jpg"
        className="rounded-lg duration-300 hover:opacity-50"
      />
    ),
  },
  {
    id: 7,
    name: "Canapé 7",
    price: "777 €",
    img: (
      <Image
        alt="table"
        width={300}
        height={300}
        src="/images/table.jpg"
        className="rounded-lg duration-300 hover:opacity-50"
      />
    ),
  },
  {
    id: 8,
    name: "Canapé 8",
    price: "888 €",
    img: (
      <Image
        alt="bureau"
        width={300}
        height={300}
        src="/images/bureau.jpg"
        className="rounded-lg duration-300 hover:opacity-50"
      />
    ),
  },
]
export const getServerSideProps = async ({ params }) => {
  const id = params.id

  const { data } = await axios.get(
    `http://localhost:3000/api/backoffice/category/${id}`
  )

  return {
    props: { data },
  }
}

const Category = (props) => {
  const {
    data: { result },
  } = props

  return (
    <>
      <Head>
        <title>AIRNEIS - Category</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex  justify-center ">
        <div className="group flex items-center justify-center ">
          <Image
            alt="canape"
            width={550}
            height={550}
            src="/images/canape.jpg"
            className="w-full   rounded-3xl p-4 "
          />
          <div className="absolute text-3xl font-black">{result.name}</div>
        </div>
      </div>
      <div className="mb-4 flex justify-center font-bold ">
        {result.description}
      </div>
      <div className="bg-orange-100 p-2 text-center  font-serif text-sm font-bold text-white md:text-lg lg:text-2xl">
        <p>
          Voici notre collection de {result.name}, cliquez sur un produit pour
          voir sa description
        </p>
      </div>

      <div className=" grid grid-cols-1 gap-3 p-4 md:grid-cols-2 lg:grid-cols-4">
        {products.map((product) => (
          <>
            <div className="flex flex-col items-center  ">
              <div className="flex  w-5/6 items-center">{product.img}</div>
              <div className="flex w-5/6 items-center justify-between ">
                <a>{product.name}</a>
                &nbsp;
                <a>{product.price}</a>
              </div>
            </div>
          </>
        ))}
      </div>
    </>
  )
}
Category.isPublicPage = true
export default Category
