import Head from "next/head"

const Category = () => {
  return (
    <>
      <Head>
        <title>AIRNEIS - Category</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
Category.isPublicPage = true
export default Category
