import Head from "next/head"
import { useTranslation } from "react-i18next"

const Category = () => {
  const { t } = useTranslation()
  return (
    <>
      <Head>
        <title>{t('categoryTitle')}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
Category.isPublicPage = true
export default Category