import Head from 'next/head'
import CarouselProduct from '@/web/components/Product/CarouselProduct'
import DescriptionProduct from '@/web/components/Product/DescriptionProduct'
import SimilarProducts from '@/web/components/Product/SimilarProducts'

const Product = ()=> {
  return (
    <>
      <Head>
        <title>AIRNEIS - Produits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex justify-between '>
      <CarouselProduct/>
      <DescriptionProduct/>
      </div>
      <SimilarProducts/>
    </>
  )
}
Product.isPublicPage = true
export default  Product
