import CarouselProduct from "@/web/components/Product/CarousselProduct"
import SimilarProducts from "@/web/components/Product/SimilarProducts"
import SingleProduct from "@/web/components/Product/SingleProduct"
import axios from "axios"
import Head from "next/head"
import { useRouter } from "next/router"
import { useEffect, useState } from "react"

const Product = ({ productId }) => {
  const [product, setProduct] = useState(null)
  const router = useRouter()

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await axios.get(
          `http://localhost:3000/api/product/${productId}`
        )
        setProduct(response.data)
      } catch (error) {
        // eslint-disable-next-line no-console
        console.error(error)
      }
    }

    if (productId) {
      fetchData()
    } else {
      router.push("/") // Redirect to homepage if no product ID is provided
    }
  }, [productId, router])

  if (!product) {
    return <div>Loading...</div>
  }

  return (
    <>
      <Head>
        <title>AIRNEIS - {product.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between lg:flex-row ">
        <CarouselProduct images={product.images} />
        <SingleProduct product={product} />
      </div>
      <SimilarProducts category={product.category} />
    </>
  )
}

export const getServerSideProps = async ({ params }) => {
  const { id } = params

  return {
    props: {
      productId: id,
    },
  }
}

Product.isPublicPage = true
export default Product
