import Layout from "@/web/components/Layout/Layout"
import Head from "next/head"

const Home = () => {
  return (
    <>
      <Head>
        <title>Airneis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout></Layout>
    </>
  )
}
Home.isPublicPage = true
export default Home
