import Head from 'next/head'
import CarouselProduct from '@/components/CarouselProduct'
import DescriptionProduct from '@/components/DescriptionProduct'
import SimilarProducts from '@/components/SimilarProducts'

const Home = ()=> {
  return (
    <>
      <Head>
        <title>AIRNEIS - Produits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex '>
      <CarouselProduct/>
      <DescriptionProduct/>
      </div>
      <SimilarProducts/>
    </>
  )
}
export default  Home